# build environment
FROM node:14.5.0-alpine as builder
WORKDIR /app
COPY package.json ./
#RUN npm i --silent
# RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install --save --legacy-peer-deps
COPY . ./
RUN npm run build:prod

# production environment
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 