apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-client-dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'nelson.murungi@fairventures.org'
    privateKeySecretRef:
      name: letsencrypt-client-dev
    solvers:
      - http01:
          ingress:
            class: nginx
